package com.pugutang.spring.boot.domain;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class ApiCode implements Serializable  {
	
	  public static final int Success = 0;
	  
	  public static final int ForbiddenCode = 403;
	  public static final String ForbiddenMessage = "请输入正确的信息";

	  public static final int UnAuthorized = 401;
	  public static final String UnAuthorizedMessage = "尚未通过身份验证, 或会话已超时";
	  public static final int BadRequestCode = 400;
	  public static final int NotFound = 404;
	  public static final int GeneralErrorCode = 100;
	  public static final String GeneralErrorString = "系统在处理请求过程中发生错误";

	  public static final int Error100 = 100;
	  public static final int Error101 = 101;
	  public static final int Error601 = 601;
	  public static final int Error604 = 604;
	  public static final int ErrorCode1000 = 1000;
	  public static final int InvalidPrivilage = 111;
	  public static final String InvalidPrivilageMessage = "权限错误";

	  public static final String BadRequestCodeMessage = "params未通过完整性校验";
	  public static final int ParamError = 500;
	  public static final int HospitalServerError = 5000;
	  public static final String InternalServerErrorMessage = "服务器遇到错误，无法完成请求";

	  public static final String BadRequestMessage = "参数'%s'非法%s";

	  public static final Object BadRequestMessageCanNotBeEmpty = "不能为空";
	  
   

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_code.code
     *
     * @mbggenerated Thu Apr 06 14:12:35 CST 2017
     */
    private Integer code;

   

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_code.code_desc
     *
     * @mbggenerated Thu Apr 06 14:12:35 CST 2017
     */
    private String msg;

   
	public Integer getCode() {
		return code;
	}
	public void setCode(Integer code) {
		this.code = code;
	}
	public String getMsg() {
		return msg;
	}
	public void setMsg(String msg) {
		this.msg = msg;
	}
	private String  data="";
	public String  getData() {
		return data;
	}
	public void setData(String  data) {
		this.data = data;
	}
	
}